name: Whatsapp_self
version: "1.3.5"
slug: whatsapp_addon_self
description: Whatsapp addon for send message from Home Assistant
url: "https://github.com/ronmichel/ha-addons-self/tree/main/whatsapp_addon"
homeassistant_api: true
hassio_api: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - config:rw
options:
  clients:
    - default
schema:
  clients:
    - str
